[build-system]
requires = ["setuptools", "Cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "pact"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "tqdm",
]

[project.optional-dependencies]
plotting = ["plotly"]

[tool.setuptools.packages.find]
where = ["."]
include = ["pact*"]
